services:

  pihole:
    container_name: "${COMPOSE_PROJECT_NAME}_pihole"
    labels:
      - traefik.enable=true
      - traefik.http.routers.pihole.rule=Host(`pi-hole.home`)
      - traefik.http.services.pihole.loadbalancer.server.url=http://127.0.0.1:8080
    image: pihole/pihole:2025.11.1
    restart: always
    environment:
      TZ: America/Sao_Paulo
      FTLCONF_webserver_domain: pi-hole.home
      FTLCONF_webserver_port: 127.0.0.1:8080
      FTLCONF_webserver_api_password: foobar
      FTLCONF_dns_listeningMode: SINGLE
      FTLCONF_dns_domain_name: home
      FTLCONF_dns_domain_local: "true"
      FTLCONF_dns_domainNeeded: "true"
      FTLCONF_dns_bogusPriv: "true"
      FTLCONF_dns_upstreams: |-
        127.0.0.1#5353
      FTLCONF_dns_hosts: |-
        192.168.0.1 router.home
        192.168.0.2 pi-hole.home
      FTLCONF_dns_cnameRecords: |-
        dnscrypt-proxy.pi-hole.home,pi-hole.home
        traefik.pi-hole.home,pi-hole.home
      FTLCONF_dhcp_active: "true"
      FTLCONF_dhcp_start: 192.168.0.50
      FTLCONF_dhcp_end: 192.168.0.150
      FTLCONF_dhcp_router: 192.168.0.1
      FTLCONF_dhcp_netmask: 255.255.255.0
      FTLCONF_dhcp_leaseTime: 1h
    volumes:
      - pihole:/etc/pihole
    network_mode: host
    cap_add:
      - CHOWN
      - NET_BIND_SERVICE
      - NET_RAW
      - NET_ADMIN
      - SYS_NICE
      - SYS_TIME

  dnscrypt-proxy:
    container_name: "${COMPOSE_PROJECT_NAME}_dnscrypt-proxy"
    labels:
      - traefik.enable=true
      - traefik.http.routers.dnscrypt-proxy.rule=Host(`dnscrypt-proxy.pi-hole.home`)
      - traefik.http.services.dnscrypt-proxy.loadbalancer.server.url=http://127.0.0.1:8081
    build:
      context: ./docker-compose/dnscrypt-proxy
    restart: always
    volumes:
      - ./docker/dnscrypt-proxy/dnscrypt-proxy.toml:/etc/dnscrypt-proxy/dnscrypt-proxy.toml
    network_mode: host

volumes:
  pihole:
