services:
  pihole:
    labels:
      - traefik.enable=true
      - traefik.http.routers.pihole.rule=Host(`pi-hole.home`)
      - traefik.http.services.pihole.loadbalancer.server.port=80
    image: pihole/pihole:2025.11.1
    restart: always
    environment:
      TZ: America/Sao_Paulo
      FTLCONF_webserver_api_password: foobar
    ports:
      - 192.168.0.2:53:53/tcp
      - 192.168.0.2:53:53/udp
    volumes:
      - pihole:/etc/pihole
    networks:
      traefik:
    cap_add:
      - CHOWN
      - NET_BIND_SERVICE
      - NET_RAW
      - NET_ADMIN
      - SYS_NICE
      - SYS_TIME

volumes:
  pihole:

networks:
  traefik:
    name: traefik
    external: true
