listen_addresses = ["0.0.0.0:5353"]

ipv4_servers = true
doh_servers = true
require_dnssec = true
require_nolog = true
require_nofilter = true

bootstrap_resolvers = ["1.1.1.1:53"]

block_ipv6 = true

cache = false

server_names = ["cloudflare-security"]

[sources.public-resolvers]
urls = [
  'https://raw.githubusercontent.com/DNSCrypt/dnscrypt-resolvers/master/v3/public-resolvers.md',
  'https://download.dnscrypt.info/resolvers-list/v3/public-resolvers.md',
]
cache_file = '/var/cache/dnscrypt-proxy/public-resolvers.md'
minisign_key = 'RWQf6LRCGA9i53mlYecO4IzT51TGPpvWucNSCh1CBM0QTaLn73Y7GFO3'
refresh_delay = 73
prefix = ''
