listen_addresses = ["127.0.0.1:5353"]

ipv4_servers = true
doh_servers = true
require_dnssec = true
require_nolog = true
require_nofilter = true

bootstrap_resolvers = ["1.1.1.1:53"]

block_ipv6 = true

cache = false

server_names = ["cloudflare"]

[sources.public-resolvers]
urls = [
  'https://raw.githubusercontent.com/DNSCrypt/dnscrypt-resolvers/master/v3/public-resolvers.md',
  'https://download.dnscrypt.info/resolvers-list/v3/public-resolvers.md',
]
cache_file = '/var/cache/dnscrypt-proxy/public-resolvers.md'
minisign_key = 'RWQf6LRCGA9i53mlYecO4IzT51TGPpvWucNSCh1CBM0QTaLn73Y7GFO3'
refresh_delay = 73
prefix = ''

[monitoring_ui]

enabled = true
listen_address = "0.0.0.0:8080"

username = ""
password = ""

enable_query_log = true
privacy_level = 1

prometheus_enabled = true
prometheus_path = "/metrics"
