services:
  traefik:
    container_name: ${COMPOSE_PROJECT_NAME}_traefik
    image: traefik:v3.6.5
    restart: always
    command:
      - --api=true
      - --log.level=ERROR
      - --entrypoints.web.address=:80
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --entrypoints.web.http.redirections.entrypoint.scheme=https
      - --entrypoints.websecure.address=:443
      - --entrypoints.websecure.http.tls=true
      - --entrypoints.websecure.asdefault=true
      - --providers.docker.exposedbydefault=false
      - --providers.docker=true
      - --providers.file.directory=/etc/traefik/providers
    volumes:
      - /run/podman/podman.sock:/var/run/docker.sock:ro
      - ./docker-compose/traefik/providers:/etc/traefik/providers:ro
      - ./docker-compose/traefik/certs:/etc/ssl/certs:ro
    network_mode: host
