services:
  traefik:
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik.rule=Host(`traefik.pi-hole.home`)
      - traefik.http.services.traefik.loadbalancer.server.port=8080
    image: traefik:v3.6.5
    restart: always
    command:
      - --api.insecure=true
      - --log.level=INFO
      - --entrypoints.web.address=:80
      - --entrypoints.web.http.redirections.entryPoint.to=websecure
      - --entrypoints.web.http.redirections.entryPoint.scheme=https
      - --entrypoints.websecure.address=:443
      - --entrypoints.websecure.http.tls=true
      - --providers.docker.exposedbydefault=false
      - --providers.docker.network=traefik
      - --providers.docker=true
      - --providers.file.filename=/etc/traefik/tls.yaml
    ports:
      - 80:80
      - 443:443
    volumes:
      - /run/podman/podman.sock:/var/run/docker.sock:ro
      - ./docker-compose/traefik/tls.yaml:/etc/traefik/tls.yaml
      - ./docker-compose/traefik/key.pem:/etc/ssl/certs/key.pem
      - ./docker-compose/traefik/certificate.pem:/etc/ssl/certs/certificate.pem
    networks:
      traefik:

networks:
  traefik:
    name: traefik
